
services:
  php:
    build:
      context: .
      dockerfile: .docker/frankenphp/Dockerfile
    ports:
      - "8001:80" # HTTP
    volumes:
      - .:/app
      - ./Caddyfile:/etc/frankenphp/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    tty: true
    environment:
      - DATABASE_URL=mysql://app:password@database:3306/app
      - APP_ENV=dev
      - APP_SECRET=abcdef123456
      - CADDY_GLOBAL_OPTIONS=auto_https off
    depends_on:
      - database

  database:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql:rw

volumes:
  db-data:
  caddy_data:
  caddy_config:
