name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
        APP_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, zip
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate Composer
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Security check
        uses: symfonycorp/security-checker-action@v3

      - name: Lint Twig templates
        run: php bin/console lint:twig templates

      - name: Lint YAML files
        run: php bin/console lint:yaml config

      - name: Lint Symfony container
        run: php bin/console lint:container

      - name: PHP-CS-Fixer
        run: composer cs:check

      - name: PHPStan
        run: composer stan

      - name: PHPUnit Tests
        run: vendor/bin/phpunit
